"""ingredients

Revision ID: c360b26fc870
Revises: 829a8568536d
Create Date: 2025-03-30 00:50:50.559727

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c360b26fc870"
down_revision: Union[str, None] = "829a8568536d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
