"""Base

Revision ID: 829a8568536d
Revises: dbfdfe0fb118
Create Date: 2025-03-26 23:10:08.708544

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "829a8568536d"
down_revision: Union[str, None] = "dbfdfe0fb118"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ingredients_in_recipes", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ingredients_in_recipes",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
